# Generated by Django 2.0 on 2020-05-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Name')),
                ('Email', models.CharField(max_length=20, verbose_name='Email')),
                ('Phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('Message', models.CharField(max_length=500, verbose_name='Message')),
            ],
        ),
    ]
