# Generated by Django 2.0 on 2020-05-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umessage',
            name='Message',
            field=models.TextField(max_length=500, verbose_name='Message'),
        ),
    ]
