# Generated by Django 2.0 on 2020-05-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200509_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='umessage',
            options={'ordering': ['-id']},
        ),
    ]
