# Generated by Django 2.0 on 2020-05-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200509_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umessage',
            name='Phone',
        ),
    ]
