# Generated by Django 2.0 on 2020-05-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_umessage_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='umessage',
            options={},
        ),
    ]
