# Generated by Django 2.0 on 2020-05-18 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200511_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='umessage',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='umessage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
    ]
